#!/usr/bin/env node
/**
 * Where this working tree stands, in a form the next session can read.
 *
 * Generated by dev-standards/sync.mjs. Do not edit here.
 *
 * Standard 10 says to hand the work over, and an instruction to remember
 * something is the weakest kind of rail there is — so this prints the handoff
 * instead of asking anyone to write it from memory. It reads git and nothing
 * else, so it is honest by construction: it cannot claim work that is not
 * committed.
 *
 * What it deliberately cannot know is what you were about to do next. That is
 * the expensive half and the only part a person has to supply, so it ends by
 * asking for exactly that and nothing else.
 *
 *   node scripts/handoff.mjs
 */

import { execFileSync } from 'node:child_process';

const git = (...args) => {
  try {
    // stderr silenced: several of these legitimately fail — no upstream set,
    // no commits yet — and git prints a fatal to the terminal even though the
    // failure is caught here. Those messages read as breakage in a report
    // whose whole job is to be trusted at a glance.
    return execFileSync('git', args, {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    // A missing upstream, a fresh repo with no commits, or no git at all. None
    // of those are worth failing over — the rest of the report still helps.
    return '';
  }
};

// `branch --show-current` rather than `rev-parse --abbrev-ref HEAD`: the
// latter fails outright in a repository with no commits yet, which is exactly
// when someone is most likely to be checking where they are.
const branch = git('branch', '--show-current') || '(no branch)';
const upstream = git('rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{u}');
const dirty = git('status', '--porcelain');
const recent = git('log', '-5', '--format=%h  %s');
const unpushed = upstream ? git('log', '--format=%h  %s', `${upstream}..HEAD`) : '';

const lines = [];
lines.push('');
lines.push(
  `Branch    ${branch}${upstream ? ` -> ${upstream}` : '   (no upstream: nothing is pushed)'}`
);
lines.push('');

if (dirty) {
  lines.push('Uncommitted, by name — every one of these is invisible to anyone else:');
  for (const line of dirty.split('\n')) lines.push(`  ${line}`);
  lines.push('');
  lines.push('  Anything here you did not change belongs to another session.');
  lines.push('  Name it and leave it alone rather than committing it (standard 7).');
} else {
  lines.push('Uncommitted   none — the tree matches the last commit.');
}
lines.push('');

if (unpushed) {
  lines.push('Committed but NOT pushed — these exist only on this machine:');
  for (const line of unpushed.split('\n')) lines.push(`  ${line}`);
} else if (upstream) {
  lines.push('Unpushed      none — everything committed is on the remote.');
}
lines.push('');

if (recent) {
  lines.push('Last commits:');
  for (const line of recent.split('\n')) lines.push(`  ${line}`);
  lines.push('');
}

lines.push('Still to write down, because git cannot know it:');
lines.push('  - what you were about to do next');
lines.push('  - anything tried and rejected, and what happened');
lines.push('  - what is unverified rather than done');
lines.push('');
lines.push('Put it where the next session will read it without being told: the');
lines.push('pull request description, or the next commit message. Not in the chat.');
lines.push('');

console.log(lines.join('\n'));
