#!/usr/bin/env node
/**
 * Can this machine actually do what this project needs?
 *
 * Generated by dev-standards/sync.mjs. Do not edit here — edit
 * `preflight.config.json`, which is this project's own and is never
 * overwritten.
 *
 * The same repository behaves differently on a laptop with a wrangler login
 * and in a browser container with neither, and the difference used to surface
 * only after something had been published. This answers it in a few seconds,
 * before anything is built.
 *
 * Self-contained on purpose. It runs inside projects that do not depend on
 * dev-standards and must not acquire a dependency on it, so the egress
 * detection below is duplicated from dev-standards/site/egress.mjs rather than
 * imported. That is a real cost, accepted because the alternative is a file
 * that only works in the repository it came from.
 *
 *   node scripts/preflight.mjs           # exit 1 only on a real blocker
 *   node scripts/preflight.mjs --deploy  # also refuse to ship an unpushed commit
 *   node scripts/preflight.mjs --json    # same, machine-readable
 */

import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const CONFIG = join(ROOT, 'preflight.config.json');
const TIMEOUT_MS = 8000;

if (!existsSync(CONFIG)) {
  console.error(
    `No preflight.config.json in ${ROOT}.\n` +
      'It is created by `node sync.mjs` in dev-standards and is this project’s own.'
  );
  process.exit(1);
}

let config;
try {
  config = JSON.parse(readFileSync(CONFIG, 'utf8'));
} catch (error) {
  console.error(`preflight.config.json is not valid JSON: ${error.message}`);
  process.exit(1);
}

const checks = [];
const record = (level, name, detail, fix) => checks.push({ level, name, detail, fix });

/**
 * An egress proxy refuses a host with a real HTTP 403, so `fetch` resolves and
 * a naive reachability test reads it as the host answering. Blocked has to be
 * its own outcome: it is the only one whose fix is outside this repository.
 */
async function probe(url) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const response = await fetch(url, { redirect: 'manual', signal: controller.signal });
    const body = await response.text().catch(() => '');
    const denied =
      response.headers?.get?.('x-deny-reason') ??
      ((response.status === 403 || response.status === 407) && /not in allowlist|egress/i.test(body)
        ? 'host_not_allowed'
        : null);
    if (denied) return { state: 'blocked', why: denied };
    return { state: 'answered', status: response.status };
  } catch (error) {
    return {
      state: 'unreachable',
      why: error.name === 'AbortError' ? 'timed out' : String(error.message ?? error),
    };
  } finally {
    clearTimeout(timer);
  }
}

// ------------------------------------------------------------ environment

for (const entry of config.env ?? []) {
  const name = typeof entry === 'string' ? entry : entry.name;
  const why = typeof entry === 'string' ? '' : (entry.why ?? '');
  const blocking = typeof entry === 'object' && entry.required === true;
  if (process.env[name]) {
    // The length only. Printing any part of a credential puts it in a terminal
    // log, a screenshot, and a transcript.
    record('ok', name, `set (${process.env[name].length} characters)`);
  } else {
    record(
      blocking ? 'block' : 'warn',
      name,
      `not set${why ? ` — ${why}` : ''}`,
      'Set it in this machine’s environment, or in the settings of the session you are in.'
    );
  }
}

// ---------------------------------------------------------------- hosts

for (const entry of config.hosts ?? []) {
  const host = typeof entry === 'string' ? entry : entry.host;
  const why = typeof entry === 'string' ? '' : (entry.why ?? '');
  const blocking = typeof entry === 'object' && entry.required === true;
  const result = await probe(`https://${host}`);
  if (result.state === 'answered') {
    record('ok', host, `answered ${result.status}`);
  } else if (result.state === 'blocked') {
    record(
      blocking ? 'block' : 'warn',
      host,
      `blocked by network policy (${result.why})`,
      `Add ${host} to this session’s network egress allowlist.${why ? ` Needed for: ${why}` : ''}`
    );
  } else {
    record(
      blocking ? 'block' : 'warn',
      host,
      result.why,
      `Check DNS and connectivity to ${host}.${why ? ` Needed for: ${why}` : ''}`
    );
  }
}

// -------------------------------------------------------------- commands

if ((config.scripts ?? []).length) {
  let pkg = {};
  try {
    pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  } catch {
    // No package.json is a fine state for a project that is not npm-based;
    // it just means the named scripts cannot exist.
  }
  for (const name of config.scripts) {
    if (pkg.scripts?.[name]) record('ok', `script: ${name}`, 'defined');
    else record('warn', `script: ${name}`, 'not defined in package.json');
  }
}

// -------------------------------------------------------------- git state

/**
 * Standard 6: a deploy names a commit that exists on the remote.
 *
 * A working tree is not a deployable artifact. Code that is live and unpushed
 * cannot be reviewed, rolled back, or rebuilt, and the next session starts
 * from a repository that does not contain it — so it gets written again,
 * differently, which is how one bug recurs across sessions that cannot see
 * each other.
 *
 * Not hypothetical. A login system was deployed to a test hostname from a
 * checkout that was never pushed; the repository it belonged to contained no
 * authentication code at all, and two sessions then spent a day debugging a
 * page neither of them could read.
 *
 * Only --deploy makes these blockers. Preflight also runs during ordinary
 * work, where a dirty tree is the normal state, and a rail that fires on the
 * normal state is the standard 4 warning that gets ignored when it matters.
 */
const deploying = process.argv.includes('--deploy');
const gitLevel = deploying ? 'block' : 'warn';

const git = (...args) => {
  try {
    return execFileSync('git', args, {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return null;
  }
};

if (git('rev-parse', '--is-inside-work-tree') === 'true') {
  const dirty = git('status', '--porcelain');
  if (dirty === null) {
    record('warn', 'git: working tree', 'could not be read');
  } else if (dirty) {
    const n = dirty.split('\n').length;
    record(
      gitLevel,
      'git: working tree',
      `${n} uncommitted file${n === 1 ? '' : 's'}`,
      'Commit them by name. Standard 7: stage the paths you edited, and leave ' +
        'changes you did not make alone rather than absorbing them.'
    );
  } else {
    record('ok', 'git: working tree', 'clean');
  }

  const head = git('rev-parse', 'HEAD');
  // Read against the local remote-tracking refs rather than the network, so
  // this works offline. A stale ref errs toward "not pushed", which is the
  // safe direction: it asks for a push that is already done, never the
  // reverse.
  const remotes = git('remote');
  const onRemote = head && remotes ? git('branch', '-r', '--contains', 'HEAD') : null;

  if (!head) {
    record('warn', 'git: pushed', 'no commit yet');
  } else if (!remotes) {
    record(
      'warn',
      'git: pushed',
      'no remote configured',
      'A local-only checkout cannot be deployed from.'
    );
  } else if (onRemote === null) {
    record('warn', 'git: pushed', 'could not be determined (shallow clone?)');
  } else if (!onRemote) {
    record(
      gitLevel,
      'git: pushed',
      `${head.slice(0, 7)} is on no remote branch`,
      'Push the branch first. A deploy names a commit someone else can check out.'
    );
  } else {
    record('ok', 'git: pushed', `${head.slice(0, 7)} is on the remote`);
  }
} else if (deploying) {
  record('warn', 'git: repository', 'not a git checkout');
}

// ---------------------------------------------------------------- report

const blockers = checks.filter((c) => c.level === 'block');

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ ok: blockers.length === 0, checks }, null, 2));
} else {
  const mark = { ok: '  ok   ', warn: ' warn  ', block: ' BLOCK ' };
  console.log(`\nPreflight — ${config.name ?? 'this project'}\n`);
  for (const c of checks) {
    console.log(`${mark[c.level]} ${c.name.padEnd(30)} ${c.detail}`);
    if (c.fix && c.level !== 'ok') console.log(`         -> ${c.fix}\n`);
  }
  if (!checks.length) console.log('  (nothing configured to check — see preflight.config.json)');
}

if (blockers.length) {
  console.error(`\nStopped: ${blockers.map((b) => b.name).join(', ')}.`);
  process.exit(1);
}
