#!/usr/bin/env node
/**
 * Compare what production is serving against what was just built, byte for
 * byte — the check standard 1 demands after every deploy.
 *
 * Generated by dev-standards/sync.mjs. Do not edit here — edit
 * `verify.config.json`, which is this project's own and is never overwritten.
 *
 * CampKitchen and mapwork each wrote their own version of this and learned the
 * same lessons a week apart, which is the drift standard 3 names. This is the
 * one copy, carrying everything both paid for:
 *
 * - **Cloudflare injects a bot-detection script** (~940 bytes, loading
 *   /cdn-cgi/challenge-platform/) into HTML it serves, so a byte-exact compare
 *   fails forever on pages that are correct. The clean fix is a WAF skip rule:
 *   zone → Security → WAF → Custom rules → HTTP header `header` equals the
 *   token → Skip: Browser Integrity Check and remaining custom rules. With the
 *   rule and the token, comparison here is byte-exact with no tolerance at
 *   all. One shared value serves every zone's rule and every repository's
 *   secret — decided 2026-08-24, reasoning in BUILD-STANDARDS section 11:
 *   this secret only skips a bot check, so the leak it guards against costs
 *   almost nothing. The per-page `tokenEnv` and `header` overrides remain
 *   for a repository spanning zones with different headers, or for isolating
 *   one zone later without touching the rest. Rotate in one pass: new value,
 *   every rule first, then every secret; the worst state in between is a
 *   release that reports unverified.
 * - **Without the token**, the one narrow tolerance is stripping that injected
 *   script before comparing: a <script> with no attributes whose body names
 *   Cloudflare's own path. Narrow on purpose — a lazy pattern would span from
 *   an inline script of ours to Cloudflare's and quietly ignore most of the
 *   page. A stale page still fails on its own bytes, and the run says plainly
 *   that it matched only after the strip.
 * - **With the token, no tolerance**: the rule should have prevented the
 *   injection, so an injected page means the rule is not working, and passing
 *   it would hide exactly that.
 * - **Bytes, not text.** Responses are compared as raw buffers, so a PNG or a
 *   woff2 compares correctly instead of being corrupted by a text decode.
 * - **Redirects are followed** (Workers static assets canonicalise
 *   /index.html to /), and the edge gets a retry tail, because ordinary
 *   propagation delay is not a failed deploy.
 *
 *   node scripts/verify-served.mjs
 */

import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const CONFIG = join(ROOT, 'verify.config.json');
const TIMEOUT_MS = 15000;
const BACKOFF_MS = [0, 2000, 4000, 8000, 15000];

/**
 * Remove Cloudflare's injected bot-detection script, and only it. Exported so
 * the test suite can pin the tolerance: the one place a widened pattern turns
 * this check into something that passes no matter what is live.
 */
export function stripInjection(html) {
  return html.replace(
    /<script>(?:(?!<\/script>)[\s\S])*?\/cdn-cgi\/challenge-platform\/(?:(?!<\/script>)[\s\S])*?<\/script>/g,
    ''
  );
}

/**
 * Decide whether a served body matches a built file. Pure, so it is testable
 * without a network: the fetch is plumbing, this is the check.
 */
export function judge(localBuf, servedBuf, { contentType = '', tokenUsed = false } = {}) {
  if (localBuf.equals(servedBuf)) return { state: 'match', detail: `${localBuf.length} bytes` };

  // The strip applies only to HTML, and only when no token was sent. With the
  // token, the WAF rule should have prevented the injection — an injected
  // page then means the rule is not working, and this check exists to say so.
  if (!tokenUsed && /text\/html/i.test(contentType)) {
    const stripped = stripInjection(servedBuf.toString('utf8'));
    if (Buffer.from(stripped, 'utf8').equals(localBuf)) {
      return {
        state: 'match',
        detail:
          `${localBuf.length} bytes, after removing Cloudflare's injected script ` +
          `(+${servedBuf.length - localBuf.length}) — set the WAF rule and ` +
          'PRODUCTION_VERIFY_TOKEN for a byte-exact compare',
      };
    }
  }

  const limit = Math.min(localBuf.length, servedBuf.length);
  let at = limit;
  for (let i = 0; i < limit; i++) {
    if (localBuf[i] !== servedBuf[i]) {
      at = i;
      break;
    }
  }
  return {
    state: 'differs',
    detail: `built ${localBuf.length} bytes, served ${servedBuf.length}, first difference at byte ${at}`,
  };
}

/**
 * Which URL, header and secret apply to one page. Per-page `base`, `header`
 * and `tokenEnv` override the config's defaults, because a repository can
 * verify more than one zone — Harp-Budget serves harpbudget.com and
 * harpfarms.com from one checkout — and per-zone secrets only work if each
 * page can name its own. Pure and exported so the override rules are pinned
 * by tests rather than trusted.
 */
export function resolvePage(config, page, env = process.env) {
  const tokenEnv = page.tokenEnv ?? config.tokenEnv ?? 'PRODUCTION_VERIFY_TOKEN';
  const token = env[tokenEnv];
  const header = page.header ?? config.header ?? 'X-Production-Verify';
  return {
    url: `${page.base ?? config.base}${page.path}`,
    headers: token ? { [header]: token } : {},
    tokenUsed: !!token,
    tokenEnv,
  };
}

async function fetchOnce(url, headers) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const response = await fetch(url, {
      redirect: 'follow',
      signal: controller.signal,
      headers: { 'cache-control': 'no-cache', pragma: 'no-cache', ...headers },
    });
    const body = Buffer.from(await response.arrayBuffer());
    return {
      status: response.status,
      body,
      contentType: response.headers.get('content-type') ?? '',
    };
  } catch (error) {
    return { error: error.name === 'AbortError' ? 'timed out' : String(error.message ?? error) };
  } finally {
    clearTimeout(timer);
  }
}

async function main() {
  if (!existsSync(CONFIG)) {
    console.error(
      `No verify.config.json in ${ROOT}.\n` +
        'It is created by `node sync.mjs` in dev-standards and is this project’s own.'
    );
    process.exit(1);
  }
  let config;
  try {
    config = JSON.parse(readFileSync(CONFIG, 'utf8'));
  } catch (error) {
    console.error(`verify.config.json is not valid JSON: ${error.message}`);
    process.exit(1);
  }

  const pages = config.pages ?? [];
  console.log(`\nServed vs built — ${config.name ?? 'this project'}\n`);
  if (!pages.length) {
    console.log('  (nothing configured to verify — see verify.config.json)');
    return;
  }

  const unset = [
    ...new Set(
      pages
        .map((p) => resolvePage(config, p))
        .filter((r) => !r.tokenUsed)
        .map((r) => r.tokenEnv)
    ),
  ];
  for (const name of unset) {
    console.log(
      `  ${name} is not set, so Cloudflare's injected script is tolerated on\n` +
        '  the HTML pages it covers and the compare is not byte-exact. Set the\n' +
        '  secret and the WAF skip rule to close that gap.\n'
    );
  }

  let failed = 0;
  for (const page of pages) {
    const { url, headers, tokenUsed } = resolvePage(config, page);
    const localPath = join(ROOT, page.file);
    if (!existsSync(localPath)) {
      console.log(` MISS   ${page.path.padEnd(18)} built file missing: ${page.file}`);
      failed++;
      continue;
    }
    const local = readFileSync(localPath);

    let outcome = null;
    for (const wait of BACKOFF_MS) {
      if (wait) await new Promise((r) => setTimeout(r, wait));
      const served = await fetchOnce(url, headers);
      if (served.error) {
        outcome = { state: 'unreachable', detail: served.error };
        continue;
      }
      if (served.status !== 200) {
        outcome = { state: 'differs', detail: `HTTP ${served.status}` };
        continue;
      }
      outcome = judge(local, served.body, { contentType: served.contentType, tokenUsed });
      if (outcome.state === 'match') break;
    }
    const mark = outcome.state === 'match' ? '  ok   ' : ' DIFF  ';
    console.log(`${mark} ${page.path.padEnd(18)} ${outcome.detail}`);
    if (outcome.state !== 'match') failed++;
  }

  if (failed) {
    console.error(
      `\n${failed} of ${pages.length} pages differ from the build. The edge is serving\n` +
        'something other than what was uploaded, or the upload has not landed.'
    );
    process.exit(1);
  }
  console.log(`\nAll ${pages.length} pages match the build.`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
